### ISSUE TITLE
Issues with location, day of the week, and sequences

### ISSUE THREAD

**Issue by FaySyedAli** [watson-developer-cloud/conversation-enhanced#101]
Hi, this is Fay from the E&D team. We were trying the ASK and had the issues below. It looks like NLU is pulling the location correctly- can the Conversation team look into this?

_The app doesnt work for Pittsburgh. I get an error message consistently of "we couldnt reach the weather company now". Can you please check?
Also, the day of the week doesnt seem to work (Fails consistently for Wednesday)
Also, it gets confused if I provide different cities in sequence and pulls the weather for a city entered much earlier rather than the most recent input._

**Comment by stevenpkg** [comment]
I think you have the wrong app, conversation with discovery dose not use NLP or check the weather?

**Comment by FaySyedAli** [comment]
@stevenpkg You're right- I posed in the wrong repo. Apologies! Moving this to closed.
