### ISSUE TITLE
How to handle access denied due to invalid credentials error?

### ISSUE THREAD

**Issue by suraj-vantigodi** [watson-developer-cloud/conversation-enhanced#106]
I followed all the steps you asked me to. But still get a error saying access denied due to invalid credentials.
I am using a trial account for discovery and conversation.
1) I have uploaded my documents in discovery.
2) Created a conversation workspace in trail conversation service.
3) created a app, 'Liberty java' pasted the username and passwords of discovery and conversation service in 
environment variables under runtime.
4) generated war file using "gradlew.bat build" command
5) modified the server.env file with my username and passwords. 
6) placed the war file and server.env files in specified folders mentioned. 
7) started the liberty server instance. 
8) visited  http://localhost:9080/dist/index.html but i get invalid credentials error

![error](https://user-images.githubusercontent.com/5551707/28911036-bf354018-784c-11e7-8a35-7fecac3648d8.png)
![connections1](https://user-images.githubusercontent.com/5551707/28911037-bf40dc98-784c-11e7-8039-539a45823bfb.png)
![conv1](https://user-images.githubusercontent.com/5551707/28911039-bf497bb4-784c-11e7-9aa7-93f6e209f17a.png)

I see that in the liberty app, under connections, there is a provision to add existing service. I selected conversations service from there. But that has different credentials. So what are the right credentials?

**Comment by stevenpkg** [comment]
When you add a connection to a service, it gets generates the necessary credentials, otherwise you can remove the connection link to the service, and add the credentials under runtime>environment variables
