### ISSUE TITLE
how to write the messageresponse in a file from this method private MessageResponse getWatsonResponse(MessageRequest request, String id) throws Exception 

### ISSUE THREAD

**Issue by vaishalisarswat** [watson-developer-cloud/conversation-enhanced#111]

**Comment by stevenpkg** [comment]
Can you please give me some more detail about what you are asking?

**Comment by vaishalisarswat** [comment]
I want to write the response of the watson service in a json file that means i want to save the chat history in a json file .
i am able to write the response only for the last conversation not for the whole conversation .

**Comment by germanattanasio** [comment]
@vaishalisarswat This is a feature request that we don't plan to support in this sample application.
If I was you I will extend the code to call the `/logs` endpoints which provide access to your conversations
