### ISSUE TITLE
Returns error when asking a discovery related question

### ISSUE THREAD

**Issue by ttlew** [watson-developer-cloud/conversation-enhanced#114]
When customer use examples provided like:

"How do I improve fuel efficiency"
OR
How do I check my tire pressure
OR
How do I turn on cruise control
OR
How do I connect my phone to bluetooth

Return Error: 

Service seems to be down.Please try again after sometime or Please check the logs.

**Comment by ttlew** [comment]
@stevenpkg are you able to check this out?

**Comment by mamoonraja** [comment]
@ttlew working! can you please confirm?

**Comment by ttlew** [comment]
Yes! @mamoonraja Thank you.
