### ISSUE TITLE
Build issue with conversation-4.2.1.jar

### ISSUE THREAD

**Issue by mageshr2016** [watson-developer-cloud/conversation-enhanced#116]
Hi - am getting build issues when I use version 4.2.1 of the jar, for this code. The following imports are not available. 

com.ibm.watson.developer_cloud.conversation.v1.ConversationService
com.ibm.watson.developer_cloud.discovery.v1.model.query.QueryResponse

But it works fine with version 3.8 of the jar. Pls guide me on which is the correct one to proceed with.  The grade build though points to version 3.8.

Thanks.

**Comment by germanattanasio** [comment]
We will update this code to use the new version but in the meantime, you can use the 3.8 version.

**Comment by germanattanasio** [comment]
@stevenpkg can you take a look at the issue?

**Comment by mageshr2016** [comment]
Thanks.

**Comment by stevenpkg** [comment]
@germanattanasio Yes I will look into this
