### ISSUE TITLE
Uploading conversation workspace fails

### ISSUE THREAD

**Issue by danifitz** [watson-developer-cloud/conversation-enhanced#119]
Hi,

I'm trying to get this demo setup in my environment. When I try to upload the conversation workspace.json file, it fails complaining that the file may not be valid json. I've tried this in several instances of the conversation service.

**Comment by danifitz** [comment]
I've managed to successfully import the workspace using this previous commit: https://github.com/watson-developer-cloud/conversation-with-discovery/commit/b952d80f5d2528250b2e82e36b7be966a4672016#diff-59365914f5f26bca88f0927f46d3504f

so there must be something wrong with the latest version...

**Comment by germanattanasio** [comment]
Thanks a lot for filing this issue! I tried the workspace and it works if you upload it using the REST API but not if you use the tool.

@stevenpkg ☝️

**Comment by stevenpkg** [comment]
Interesting I will take a look

**Comment by stevenpkg** [comment]
@danifitz how are you downloading the workspace, I seem to remember an issue with just downloading the workspace by itself from github, the solution was to download the project as a zip file and get the workspace from there?

**Comment by danifitz** [comment]
Hi,
I got the `workspace.json` file by cloning the repo and then when using the UI upload tool, navigating to the cloned directory on my laptop.

**Comment by Oliver-I** [comment]
@danifitz The workspace.json file has been updated. Please try importing with the new workspace. If you are still having issues, rather than cloning, simply download the zip, then extract the files and import the workspace.json file from the extracted folder.

**Comment by danifitz** [comment]
works now, thanks for fixing!
