### ISSUE TITLE
not calling retreive and rank when i type the question How do I turn on cruise control

### ISSUE THREAD

**Issue by nishinair123** [watson-developer-cloud/conversation-enhanced#38]
The app is not calling RnR when I type the question 

> How do I turn on cruise control.

But I can rank and view the answer in the service. 
Could you help to debug?

**Comment by germanattanasio** [comment]
Seems to be working for me. <img width="875" alt="screen shot 2016-09-10 at 9 02 41 pm" src="https://cloud.githubusercontent.com/assets/313157/18415067/f160f76c-7799-11e6-908d-a38200086c88.png">
