### ISSUE TITLE
Conversation

### ISSUE THREAD

**Issue by sayurimizuguchi** [watson-developer-cloud/conversation-enhanced#42]
Hello, 
if i dont use the  Retrieve and Rank services to use Watson, which files have to use?

Thanks.

**Comment by dgterry** [comment]
Hello,
Are you simply wanting to use the app for Conversation only? If so you can essentially comment out the if block starting here: https://github.com/watson-developer-cloud/conversation-enhanced/blob/master/src/main/java/com/ibm/watson/apis/conversation_enhanced/rest/ProxyResource.java#L125
that will force the app to never call R&R and always return the Conversation response.

You might be interested in exploring the https://github.com/watson-developer-cloud/conversation-simple application which only uses conversation.
