### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sayurimizuguchi** [watson-developer-cloud/conversation-enhanced#43]
Hello,
I can not find where places workspace_id and displays this error when I run

Error:WORKSPACE_ID not set
See steps on Github for adding an environment variable

**Comment by sayurimizuguchi** [comment]
i cant find environment variable for insert workspace_id

**Comment by sayurimizuguchi** [comment]
In the logs:
App/0[WARNING ] SRVE0190E: File not found: /dist/locale/pt.json

when i open the project, the navigator show me " SRVE0190E: File not found: /dist/locale/pt.json"
where I put this file? or it already exists? I not found within the project, or I have to edit the existing (.json) within the folder?

**Comment by dgterry** [comment]
Hello,

It sounds like there are two problems here? I would think we would want to address the WORKSPACE_ID one first.  I assume you are getting that when you start the app? If so you need to set the WORKSPACE_ID.  Are you running the application in bluemix or locally? 
If bluemix see: https://github.com/watson-developer-cloud/conversation-enhanced#adding-environment-variables-in-bluemix
If locally see step 6 of: https://github.com/watson-developer-cloud/conversation-enhanced#running-locally
You can get the WORKSPACE_ID from the Conversation service tooling.  Here are some instructions: https://github.com/watson-developer-cloud/conversation-enhanced#workspaceID

I'd recommend setting that, restarting the app, and see if things work for you.  We then can troubleshoot other issues if you still have them.

**Comment by sayurimizuguchi** [comment]
I try in bluemix application, not locally.
And I import the project and when I run app, show me error: Error: "WORKSPACE_ID not set
See steps on Github for adding an environment variable"
I see this but i dont find the "enviroment variable" for insert the workspace_id.

if i want modify the workspace id for my ibmbluemix create conversation, in this case, what do I do?

**Comment by dgterry** [comment]
Okay great, the first thing you will want to do is get the WORKSPACE_ID from the Conversation tooling.  Here are a few steps to do that: https://github.com/watson-developer-cloud/conversation-enhanced#import-a-workspace
you can ignore steps 3 & 4 as you aren't importing a workspace.  I'd focus mostly on the screenshots in this section which will show you how to get the workspace id once you are in the tooling.  

Once you have the id you will need to set it.  The documentation looks like it is describing how to set the ENV using the older Bluemix UI.  Here are some updated instructions:

-go to your bluemix dashboard
-find the name of your application, click on the row for it to open the application details
-click on runtime in the left column
-along the top, click the environment variables tab (you might have to scroll up in the right frame to see it)
-scroll down to the bottom until you see the user defined section
-click add and then type WORKSPACE_ID for the name and then paste the workspace id you obtained earlier into the value portion
-click save

This should restart the app and it should now be connected to your workspace. Please let us know how things go.

**Comment by sayurimizuguchi** [comment]
Hi, great, I saw an update of its "readme.md" a girl. And it worked.
open my file :dancing_men: .

But now show me the error: file not found /locale/pt.json and repeat the primary message...
I did file (pt.json) and put together the (en.json) for testing, but it has this error.
It has something to do with changing the server language?

**Comment by sayurimizuguchi** [comment]
The update: https://github.com/watson-developer-cloud/conversation-enhanced/pull/44

**Comment by sayurimizuguchi** [comment]
![errorptjson](https://cloud.githubusercontent.com/assets/23122214/19904129/92a14ba4-a058-11e6-87c3-d2d9436de471.PNG)

**Comment by dgterry** [comment]
Hi, yes I believe the application was created with support for other languages but that only English strings were provided. Looks like you changed the language to Portuguese? I believe that is making the app look for a pt.json containing translated versions of the strings located in en.json. I wonder if you could simply copy the en.json to pt.json and see if that helps.  Perhaps you were saying you already did that in your previous message and you still experienced errors? Is the app working correctly for you if everything is set to English?

**Comment by sayurimizuguchi** [comment]
hello David, good morning.
So in this case you're talking to edit the file and en.json translate? Or create another file? Because I tried to create another file translating everything that is in en.json and put in the same folder, only it did not work. I will perform some tests while I await your response. Thank you for everything!

**Comment by sayurimizuguchi** [comment]
Obs.: The application runs even with the error, perfectly.

**Comment by sayurimizuguchi** [comment]
David, if I try execute locally, but i dont want use the rank-service, just the conversation in webpage, I reconfigured or i delete what?

I'm sorry for the english, i'm from Brazil - PT-br.

**Comment by sayurimizuguchi** [comment]
Locally:

I execute the grap .bat, didn't work.
I download in the https://services.gradle.org/distributions the file  "gradle-2.14.1-bin.zip" and ok.
I save
I try execute locally but i dont find archive conversation-enhanced-0.1-SNAPSHOT.war in the conversation-enhanced/build/libs/ folder. 
there is not even the folder "build" in conversation-enhanced

I copy the server.env with the informations from watson ibm bluemix to libery (usr/servers/(my name server) and ok.

But, if execute in the IDE Netbeans, shows me the message:
"Go to Github Go to Github
Loading..."

I need to execute locally, the company I work for is looking to work on projects with Watson.

**Comment by dgterry** [comment]
Hi! If you just want Conversation the easiest way to do that is to probably look at this repo instead: https://github.com/watson-developer-cloud/conversation-simple as it is built using only the Conversation service.  However, I understand if you want to continue to use this one because you have already invested effort or perhaps because you prefer Java. 

If you want to disable R&R in this app I believe there are two things you will need to do.

1) You will want to stop the setup from looking for R&R pieces when the app starts. You should be able to do this by going into SetupThread.java and looking at the run method.  I think you could either comment everything in that method out, or simply put a return; at the beginning of the method so it doesn't do anything.

2) You will want to prevent calls to R&R.  You can do this by opening up the ProxyResource.java file and commenting out the if section that determines if R&R should be called (it's in the getWatsonResponse method on lines 125 to 150). 

It looks like you are also experiencing some trouble building the application? What operating system are you on? You mentioned the .bat file so I assume you are on Windows?  Could you cd into the conversation-enhanced directory and run `gradlew.bat build` and send me the output if there are any errors?

**Comment by sayurimizuguchi** [comment]
Thanks David for the informations. 
But, in the conversation-simple i can modify and validate informations if user write incorret? example: CPF xxx.xxx.xxx-xx

And yes, I prefer java, hehe.. but it's not so important if i can use the watson in webpage corretly just with javascript+html of course.

I do your option with "cd" command in Windows and before showed me:
![gradlwbatexecutecmd](https://cloud.githubusercontent.com/assets/23122214/19972255/8d5a3694-a1c8-11e6-85b0-ca2e9ddd4471.JPG)

**Comment by dgterry** [comment]
Hello,

I'm not sure I understand your question regarding the conversation-simple app.  Could you possibly rephrase it? 

As for the build error it looks like it can't download the gradle zip it needs to perform the build.  Could that potentially be a firewall issue? 

I also think it would help if you could 
cd into the C:\Users\marcia.martins\Desktop\Wattester and run the `gradlew.bat build` while Wattester is the current directory. The script will assume certain things are in the current working directory and it will likely cause problems if that is your home directory.

**Comment by sayurimizuguchi** [comment]
Example, I want use watson just for conversation and if the "user" write corretly it (watson) returns the correct answer

I got it (install gradlew.bat) and i copy the (.war) to the liberty (i paste the liberty inside the project Wattester), 
Steps i got:

1 Git clone the project https://github.com/watson-developer-cloud/conversation-enhanced

2 Navigate to the conversation-enhanced folder

3 For Windows, type gradlew.bat build. Otherwise, type gradlew build.

If you prefer, use your locally installed Gradle plugin instead of this provided wrapper.
4 The built WAR file (conversation-enhanced-0.1-SNAPSHOT.war) is in the conversation-enhanced/build/libs/ folder.

Running locally

1 Copy the WAR file generated above into the Liberty install directory's dropins folder. For example, <liberty install directory>/usr/servers/<server profile>/dropins.

2 Navigate to the conversation-enhanced/src/main/resources folder. Copy the server.env file.

But, I could not execute the server run (name server: Wattester) before this. 
"7 Start the server using Eclipse or CLI with the command server run <server name> (use the name you gave your server)."

error: 
"Go to Github Go to Github
Loading..."

:\

**Comment by sayurimizuguchi** [comment]
![wattesterimagemeforegrandel](https://cloud.githubusercontent.com/assets/23122214/19979156/9df3bb66-a1e0-11e6-9fed-db95e8367c4d.JPG)

**Comment by dgterry** [comment]
Hello,
So both this app and the https://github.com/watson-developer-cloud/conversation-simple use the Conversation service to answer questions. The only difference, besides this app being written in Java and the simple app being written in node, is that this enhanced app will send questions to R&R if Conversation is not able to provide a meaningful answer. So it sounds like the simple conversation app could achieve your objectives.  It might be simpler since you don't need to get an external server like liberty.

As for where you are with this app it sounds like you have:
- installed liberty
- are able to build the war
- are able to copy the war into the appropriate folder in liberty (dropins)
- but you are unable to start the liberty server

do I have that correct? I guess I'm mostly unclear on where and when you are seeing this error:

``` error:
"Go to Github Go to Github
Loading..."
```

I don't believe liberty should be sending you to github...that sounds like something in the UI? The error that tells you to set your WORKSPACE_ID? Maybe you need to add your workspace id to the server.env file before you copy it into liberty and start the server?

**Comment by sayurimizuguchi** [comment]
Exactly, I can not run server Liberty, show me the error "go to Hube git" when I run the application in netbeans. How do I run the server locally liberty?

**Comment by sayurimizuguchi** [comment]
![error](https://cloud.githubusercontent.com/assets/23122214/19981616/cca8a256-a1e9-11e6-9aa6-9aedd352581a.JPG)

**Comment by sayurimizuguchi** [comment]
I will try use the conversation simple, but I want use this conversaion-enhanced because i will use java :\

**Comment by dgterry** [comment]
Sure, just mentioned conversation-simple as another possible option for you.  I understand if you wish to use this app.  For now maybe it is easiest to run liberty standalone, outside of an IDE like netbeans or eclipse.  Can you see if this helps you:
1. Goto https://developer.ibm.com/wasdev/downloads/liberty-profile-using-non-eclipse-environments/
2. Click the download button in the middle of the page to get a copy of liberty
3. Decompress it
4. copy the war you previously built with `gradlew.bat build` to <folder you decompressed this in>\wlp-webProfile7-16.0.0.3\wlp\templates\servers\defaultServer\dropins
5. copy the server.env file containing your WORKSPACE_ID to <decompressed root>\wlp-webProfile7-16.0.0.3\wlp\usr\servers\defaultServer
   if you need help finding/setting up this file see steps 2 through 6 here: https://github.com/watson-developer-cloud/conversation-enhanced#running-locally
6. in a command line window navigate to <where you decompressed this>wlp-webProfile7-16.0.0.3\wlp\bin
7. type `server run` and press enter
8. look for lines in the console output that look like this:
   [AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/
   [AUDIT   ] CWWKZ0009I: The application conversation-enhanced-0.1-SNAPSHOT has stopped successfully.
9. navigate to whatever that URL is, http://localhost:9080 by default

you should now see the application running. If you didn't comment out the run() method in SetupThread it will now try to setup R&R for you.  If that happens see this comment: https://github.com/watson-developer-cloud/conversation-enhanced/issues/43#issuecomment-258160595

**Comment by sayurimizuguchi** [comment]
Good morning Davi, i do this. But presents me error now.

I have to run the command gradlew.bat within the defaultserver folder?

I do your steps and presents me:
![error](https://cloud.githubusercontent.com/assets/23122214/20003945/6dbe1e10-a270-11e6-8c33-bc97a4b8d6e1.JPG)

**Comment by sayurimizuguchi** [comment]
Obs.: I'm trying to open a conversation that I made with my credentials Watson username and password

**Comment by sayurimizuguchi** [comment]
and I set the server.env with the correct credentials, but it seems to have set in SetupThread, I tried to do this by saving the information, but there have to put the password and username rank and Service or Conversation?

**Comment by sayurimizuguchi** [comment]
Sorry Davi, the problem it was a proxy... now shows the error by Workspace_id
I'll try to fix...

**Comment by sayurimizuguchi** [comment]
It seems that when I run the server run, it resets the configuration of the conversation in server.env I put

**Comment by sayurimizuguchi** [comment]
I paste the server.env with the informations corretly of mine conversation, but when I run the command "server run" the server.env I tagged along, resets the settings made in it the correct information

C:\Users\marcia.martins\Desktop\wlp\usr\servers\defaultServer\apps\expanded\conversation-enhanced-0.1-SNAPSHOT.war\WEB-INF\classes = server.env (resets automatically)

**Comment by sayurimizuguchi** [comment]
Hello Davi, thanks. I do all the things, but if I execute Server run, ok, but when I open the page, shows me the error: Workspace_id

![workspaceid](https://cloud.githubusercontent.com/assets/23122214/20010134/2b3bcdc6-a28e-11e6-99fa-1a4b2513dd31.JPG)


And the messages in server - wlp:
![error](https://cloud.githubusercontent.com/assets/23122214/20010164/3c4fde86-a28e-11e6-8e5b-581a1eac91dd.JPG)

**Comment by sayurimizuguchi** [comment]
Obs.: I put the information within the server.env as requested. follow print
![serverenv](https://cloud.githubusercontent.com/assets/23122214/20010330/d529605a-a28e-11e6-995b-02362f6f1ad0.JPG)

**Comment by sayurimizuguchi** [comment]
Hi Davi, 
I can run locally. But I wonder how that node is to keep what is typing in a id "node_1_1477578976409" because I want to know a way to treat the information that Watson understands.

Example:
I digite: I want pizza pepperoni. = "node_1_1477578976409"

I want save the information in one variable to run any script... You can help me?

**Comment by mitchmason** [comment]
node ids are generated by the service automatically. You really don't need to do anything with them in your app. Its not advised becuase there is no easy way to know which node has which node id. The best way to use nodes to do a script is to set a context flag on the dialog node that your app is listening for. 
Something like this:
"context": {
"topping": @topping,
"size": @size,
"callDB": true
}
and your app is constantly listening for "callDB" to be set to true, and when it sees that it can go off and run your script. You can call this varibale whatever you like as long as your app is listening for it. 

Also, in the future, we have these forums for questions about how to use the service:
https://developer.ibm.com/answers/index.html
please ask these types of questions there as they are more visible for everyone to learn from. If you have technical questions about deploying the app, github is the right place. For how to use the service, please use the forums.

**Comment by Topping** [comment]
I fail to see how I'm relevant here - But thanks for the mention @mitchmason.

**Comment by mitchmason** [comment]
hahaha sorry, didnt realize you were a person. was just showing how he could write an entity for a pizza topping in conversation service.

**Comment by dgterry** [comment]
Going to close this one as the app is now running locally.  Conversation questions can be directed to the forums: https://developer.ibm.com/answers/index.html

**Comment by sayurimizuguchi** [comment]
Hi Davi,
Today i try execute locally after edit the conversation in my bluemix, and, when I execute the command "server run" in /wlp/bin, and try to open the localhost in the browser, it presents the error that is in the print:

![error](https://cloud.githubusercontent.com/assets/23122214/20184963/8061d3dc-a751-11e6-9fc2-fc1e77491510.JPG)


You can help me please?

**Comment by sayurimizuguchi** [comment]
Is there any way I can execute only by netbeans with the project files? Even after you have modified some classes and the conversation?
