### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sayurimizuguchi** [watson-developer-cloud/conversation-enhanced#48]
Hi Davi,
Today i try execute locally after edit the conversation in my bluemix, and, when I execute the command "server run" in /wlp/bin, and try to open the localhost in the browser, it presents the error that is in the print:

![erro server ri](https://cloud.githubusercontent.com/assets/23122214/20224303/f6df30ee-a824-11e6-8f11-b66c17f97622.JPG)

**Comment by dgterry** [comment]
Hello,
Could this potentially be a firewall issue? gateway.watsonplatform.net maps to 158.85.132.88 and it appears to be a connection problem to that IP. I believe you mentioned you had a proxy in place before? Perhaps an issue with that?

**Comment by sayurimizuguchi** [comment]
Exactly, Davi, thank you.
I did a test accessing the site and gave a proxy error, I requested that it be released.
At home it works normally.
I am wanting to build a similar application, any tips?
Can I use your project as a help?

**Comment by sayurimizuguchi** [comment]
I'm trying to run the project with some modified files, with eclipse, and it gives me this error:
![errorpageeclipse](https://cloud.githubusercontent.com/assets/23122214/20227340/2ade1a3c-a833-11e6-9096-ab89eb9b586b.JPG)

**Comment by sayurimizuguchi** [comment]
I'm trying to run the project with some modified files, with eclipse, and it gives me this error:
![errorpageeclipse](https://cloud.githubusercontent.com/assets/23122214/20227407/5025b19c-a833-11e6-96e2-4c3d77fe28cf.JPG)
