### ISSUE TITLE
Deploy to bluemix

### ISSUE THREAD

**Issue by ReeceMed** [watson-developer-cloud/conversation-enhanced#54]
Hi, 

I am interested in creating a similar deploy to bluemix button for the watson conversation simple version. However i am running into issue with creating the services, do you have any information on how i can achieve this?

**Comment by dgterry** [comment]
Hello,

The button is essentially a URL instructing bluemix where to find the application code. For example, I just used this URL to deploy the simple application: https://bluemix.net/deploy?repository=https://github.com/watson-developer-cloud/conversation-simple

once it completes you can click view app and it should load up.  You will need to follow the instructions about setting a WORKSPACE_ID but the deploy seems to work.

If this isn't working for you please provide any details on the creating services issue you mentioned.

**Comment by germanattanasio** [comment]
I'm closing this since an answer was already provided
