### ISSUE TITLE
Is there a blog post about this?

### ISSUE THREAD

**Issue by Twanawebtech** [watson-developer-cloud/conversation-enhanced#55]
Are you planning to blog about this? the demo is good and I love it...

**Comment by dgterry** [comment]
Thanks very much for the kind words! @mitchmason any thoughts on this?

**Comment by mitchmason** [comment]
This demo was released at the same time the service went GA, it is a very powerful interaction to have both short tail and long tail like this, but I think at this point we will not release another blog about this demo specifically at this time. As we make enhancements and hcanges to things we will be sure to blog about them on the watson blog.
