### ISSUE TITLE
Build fails while trying to deploy on blue mix

### ISSUE THREAD

**Issue by chandrachood** [watson-developer-cloud/conversation-enhanced#60]
I could deploy this App when Blue mix was on DEA , Now after it moved to Diego when I try to deploy it again it was showing the following error . 

Download http://repo1.maven.org/maven2/xalan/xalan/2.6.0/xalan-2.6.0.jar
Download http://repo1.maven.org/maven2/com/ibm/icu/icu4j/2.6.1/icu4j-2.6.1.jar
:findbugsMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':findbugsMain'.
> FindBugs rule violations were found. See the report at: file:///home/pipeline/f1354224-5d67-4a0e-99fe-25a53aef37f3/build/reports/findbugs/main.xml

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 27.22 secs

Finished: FAILED**

**Comment by germanattanasio** [comment]
I'm working on this.
