### ISSUE TITLE
Discovery service returns no results for long-tail questions sent from Conversation service

### ISSUE THREAD

**Issue by alexandru-anastasopol** [watson-developer-cloud/conversation-enhanced#69]
Hello,

I have run into an issue - Discovery service not returning results for long-tail questions.

After deploying this application on Bluemix, following the delpoyment instructions, the answer for "How do I check my tire pressure" is "That question is out of scope for this application, take a look at the Conversation Enhanced application to handle questions like these.", which is not expected. Doing a direct query on the Discovery service returns relevant results from the car manual 

Also, when asking the same question on the official application page (at http://conversation-with-discovery.mybluemix.net/dist/index.html) the answer is "Great question. I found some ideas for you:", followed by relevant sections from the car manual.

The value for "CEPayload" (on the right pane, "Watson understands" section) is empty in the first case (the application deployed on my Bluemix account) and contains the relevant sections from the car manual in the second case (official website).

Please see attached screenshots below.

![conversationwithdiscoverybluemixdeployment_issue](https://cloud.githubusercontent.com/assets/26007725/23657149/62f06bf6-0345-11e7-8c60-bdc401535a76.png)
![discoveryservicequerybluemixdeployment_working](https://cloud.githubusercontent.com/assets/26007725/23657148/62eec2d8-0345-11e7-824f-85bcc339f9d1.png)
![conversationwithdiscoveryofficialwebsite_working](https://cloud.githubusercontent.com/assets/26007725/23657147/62ee49ca-0345-11e7-8f43-582f2681e411.png)

Thank you.

**Comment by ddacosta79** [comment]
I have exactly the same issue.
Did you find the cause?

David

**Comment by alexandru-anastasopol** [comment]
Hi David,

I found the cause: 
The actual query sent to Discovery service is: "searchText:\<user query\>, enrichedText:\<userQuery\>"
see the project code: at `DiscoveryQuery.query(String userQuery)` at lines:
```
        sb.append("searchText:");
        sb.append(userQuery);
        sb.append(",");
        sb.append("enrichedText:");
        sb.append(userQuery);

```
Executing that exact query directly on the Discovery service will not return any results either. For some reason the "enrichedText" field is not added to the processed JSON collection.

Hope this helps,
Alex

**Comment by mitchmason** [comment]
If your docs are not well trained, or the question gets extremely low confidence returned, discovery will not send any results, thus none will be showed. we should write additional code to handle that scenario. 
other htan that, looks like Alex found the issue already.

**Comment by 619** [comment]
Might you suggest an actual solution?
