### ISSUE TITLE
Embedding into html

### ISSUE THREAD

**Issue by renderit** [watson-developer-cloud/conversation-enhanced#70]
Hey great work here! Wanted to ask about embedding into an html page. I have a dialog setup and running on watson. In this repository, have you created the frontend UI yourself, and then calling the services via REST?

**Comment by mitchmason** [comment]
Yes, thats exactly whats happening. The app code also orchestrates the calls between conversation and discovery.
You could take this UI and embed it as an iframe, or create your own chat widget and use the API directly.
