### ISSUE TITLE
add case to handle low confidence/no results from discovery

### ISSUE THREAD

**Issue by mitchmason** [watson-developer-cloud/conversation-enhanced#75]
currently, if discovery is giving back poor results, it returns an empty array i think, need to update this to at least give a message to user saying no results found or something like that.

**Comment by Oliver-I** [comment]
@stevenpkg This will need to be added in your code, unfortunately the workspace doesn't handle/display the Discovery result.

**Comment by stevenpkg** [comment]
Good idea, will implement

**Comment by stevenpkg** [comment]
have implemented this now, see pull request #92
