### ISSUE TITLE
I am getting an error importing the workspace.json to conversation.  Unable to parse input

### ISSUE THREAD

**Issue by benjamincjacob** [watson-developer-cloud/conversation-enhanced#76]

**Comment by benjamincjacob** [comment]
The previous version will import without error.

**Comment by germanattanasio** [comment]
@stevenpkg this is the same problem as with `conversation-simple`. I think we should add a test case to make sure we doesn't submit changes using a non-working `workspace.json`

**Comment by stevenpkg** [comment]
@germanattanasio yes will look at .gitattributes and see about putting a test case in

**Comment by mageshr2016** [comment]
I still have the same issue. Can you pls let me know which version to try to input?
