### ISSUE TITLE
wrong service names in manifest.yml

### ISSUE THREAD

**Issue by vnordin** [watson-developer-cloud/conversation-enhanced#78]
I just forked this project by using the "deploy to bluemix"-button and noticed that the Deploy-stage failed since it wasn't able to bind the services. The services that are automatically created are named "conversation-service" and "discovery-service" but in the manifest.yml they are named "my-conversation-service" and "my-discovery-service", so I had to rename them to make it work.

**Comment by germanattanasio** [comment]
Nice point @vnordin I don't know how this happened. 

@stevenpkg Can you please fix the `README.md` and `manifest.yml` so that we create and use the same services?

**Comment by stevenpkg** [comment]
Yes pipeline.yml was creating conversation-service and discovery-service, have changes manifest.yml to have the same naming
