### ISSUE TITLE
could you please add instructions to run in a different servlet container?

### ISSUE THREAD

**Issue by pgoldweic** [watson-developer-cloud/conversation-enhanced#90]
I'd like to try this application but running under the Tomcat servlet container. Would be great to see instructions on how to do that (or, non-container specific instructions of how to run the war file as a web application in any container).

**Comment by stevenpkg** [comment]
We do not want to make things to complex, the main thing is to understand Conversation and Discovery services. If anyone out there has time to get this running with Tomcat, please share.
