### ISSUE TITLE
custom config instructions

### ISSUE THREAD

**Issue by ghost** [watson-developer-cloud/conversation-enhanced#91]
In the custom.config instructions, under the Normalize section, the fields "body_enriched.keywords.text" and "body_enriched.concepts.text" may need to be changed to fields: "enriched_body.keywords.text" and "enriched_body.concepts.text" (the latter fields are supplied in the dropdown menu).

**Comment by stevenpkg** [comment]
will look into this, thank you

**Comment by stevenpkg** [comment]
All seems good to me when I follow the advanced Discovery config setup
