### ISSUE TITLE
Incorrect curl command

### ISSUE THREAD

**Issue by cvsanchez42** [watson-developer-cloud/conversation-enhanced#97]
https://github.com/watson-developer-cloud/conversation-with-discovery/blob/master/custom_config/config_instructions.md#set-up-a-custom-configuration-with-the-discovery-api

In the terminal command:
-There is an invalid quote character, and quotes are missing.
- -data should be --data
- not sure if all the arguments are laid out correctly

**Comment by stevenpkg** [comment]
Always good to retype as copy and paste can course errors. Try this

curl -X POST -u “<username>:<password>” \
-H “Content-Type: application/json” \
-data “@<path_to_config>” \
“https://gateway.watsonplatform.net/discovery/api/v1/environments/<environment_id>/configurations?version=2016-12-01”
