### ISSUE TITLE
Error when i compile the project 

### ISSUE THREAD

**Issue by jrzam92** [watson-developer-cloud/conversation-enhanced#99]
Hi i m using the project but  when i compile the project with the command in the console show this:
```
npmSetup SKIPPED
:npmInstall
npm WARN deprecated angular2@2.0.0-beta.21: This version of Angular has been deprecated. Use @angular/core instead.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated fs-promise@0.3.1: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```
I suppose that I need to install I new version of those packages but is with the command `npm install` ?

**Comment by stevenpkg** [comment]
These are just warnings, and will not prevent the demo from running. Will look at updating in the near future

**Comment by germanattanasio** [comment]
Don't worry about the warnings. They are coming from some of the libraries that we use to build the UI but they don't affect the app
